name: Build query-engine
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: prismagraphql/build:debian-libssl1.1.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build query-engine-node-api
        run: |
          rustup default stable
          cargo build --release -p query-engine-node-api
      - name: List Target
        run: |
          ls -lh target/release/
          
      - name: "Upload build"
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: target/release/libquery_engine.so