name: Build query-engine
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: prismagraphql/build:debian-libssl1.1.x
    steps:
         - name: Log the OS version
           run: |
             cat /etc/os-release  


