name: Build query-engine
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: prismagraphql/build:debian-libssl1.1.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build query-engine-node-api
        run: |
          rustup default stable
          cargo build --release -p query-engine-node-api
      - name: List Target
        run: |
          ls -lh target/release/